language: rust
rust:
- stable
- nightly
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - wget http://www.guillaume-gomez.fr/fmodapi44439linux.tar.gz
  - tar xvf fmodapi44439linux.tar.gz
  - sudo cp -r fmodapi44439linux/api/lib/* /usr/local/lib/.
script:
  - rustc --version
  - cargo build
  - cd examples
  - cargo build
  - cd ..
  - cargo doc
